models/PhoneForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * Модель формы создания/изменения записи в телефонном справочнике
 */
class PhoneForm extends Model {

	public $name;
	public $phone;
	public $email;

	/**
	 * @inheritdoc
	 *
	 * @return array
	 */
	public function rules() {
		$rules = [
			[['name', 'phone'], 'required', 'message' => 'Заполните поле'],
			['email', 'email', 'message' => 'Неправильный формат {attribute}']
		];

		return $rules;
	}

	/**
	 * @inheritdoc
	 *
	 * @return array
	 */
	public function attributeLabels() {
		return [
			'name'	    => 'ФИО',
			'phone'		=> 'Номер телефона',
			'email'		=> 'E-mail',
		];
	}

}

models/Phones.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use yii\data\Pagination;

/**
 * Телефонный справочник
 *
 * @property int    $id
 * @property string $name   ФИО
 * @property string $phone  Мобильный номер телефона
 * @property string $email  E-mail
 */
class Phones extends ActiveRecord {

	/** Количество записей на одну страницу */
	const PER_PAGE = 20;

	/**
	 * Получения списка записей телефонного справочника
	 *
	 * @return array
	 */
	public function getList() {
		$query = self::find();

		$pagination = new Pagination([
			'route' => 'phones/index',
			'forcePageParam' => false,
			'defaultPageSize' => self::PER_PAGE,
			'totalCount' => $query->count()
		]);

		$phones = $query
			->orderBy(['id' => SORT_DESC])
			->offset($pagination->offset)
			->limit($pagination->limit)
			->all();

		return [
			'phones' => $phones,
			'pagination' => $pagination
		];
	}

	/**
	 * Получение одной записи
	 *
	 * @param int $id Идентификатор записи в телефонном справочнике
	 *
	 * @return array|null|ActiveRecord
	 */
	public function getOne($id) {

		$query = self::find();
		$phone = $query
			->where(['id' => $id])
			->one();

		return $phone;
	}

}

controllers/PhonesController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Response;
use yii\web\Controller;
use app\models\Phones;
use app\models\PhoneForm;

/**
 * Контроллер для работы с телефонным справочником
 */
class PhonesController extends Controller {

	/**
	 * Страница телефонного справочника
	 *
	 * @return string
	 */
	public function actionIndex() {
		$phones = new Phones();

		return $this->render('index', $phones->getList());
	}

	/**
	 * Создание записи в телефонном справочнике
	 *
	 * @return array
	 */
	public function actionCreate() {
		$phoneForm = new PhoneForm();

		if($phoneForm->load(Yii::$app->request->post()) && $phoneForm->validate()) {
			$phones = new Phones();

			$phones->name = $phoneForm->name;
			$phones->phone = $phoneForm->phone;
			$phones->email = $phoneForm->email;
			$phones->save();

			$phoneId = $phones->id;

			if($phoneId !== false) {
				if(Yii::$app->request->isAjax === true) {
					Yii::$app->response->format = Response::FORMAT_JSON;

					return [
						'success' => true,
						'phoneId' => $phoneId,
						'content' => $this->renderPartial('index', $phones->getList()),
					];
				}
			}
		}

		return $this->renderAjax($this->action->id, [
			'phoneForm' => $phoneForm,
		]);
	}

	/**
	 * Изменение записи в телефонном справочнике
	 *
	 * @return array
	 */
	public function actionUpdate() {
		$id = Yii::$app->request->get('id');

		$phones    = new Phones();
		$phoneForm = new PhoneForm();
		$phone     = $phones->getOne($id);

		$phoneForm->name = $phone->name;
		$phoneForm->phone = $phone->phone;
		$phoneForm->email = $phone->email;

		if($phoneForm->load(Yii::$app->request->post()) && $phoneForm->validate()) {
			$phone->name  = $phoneForm->name;
			$phone->phone = $phoneForm->phone;
			$phone->email = $phoneForm->email;
			$phone->save();

			$phoneId = $phone->id;

			if($phoneId !== false) {
				if(Yii::$app->request->isAjax === true) {
					Yii::$app->response->format = Response::FORMAT_JSON;

					return [
						'success' => true,
						'phoneId' => $phoneId,
						'content' => $this->renderPartial('index', $phones->getList()),
					];
				}

			}
		}

		return $this->renderAjax($this->action->id, [
			'phoneForm' => $phoneForm,
		]);
	}

	/**
	 * Удаление записи из телефонного справочника
	 *
	 * @return array
	 */
	public function actionDelete($id = false) {
		Yii::$app->response->format = Response::FORMAT_JSON;

		$phones = Phones::find()->where(['id' => $id])->one();
		$phones->delete();

		return [
			'success' => true,
			'content' => $this->renderPartial('index', $phones->getList()),
		];
	}
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
	<head>
		<meta charset="<?= Yii::$app->charset ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?= Html::csrfMetaTags() ?>
		<title><?= Html::encode($this->title) ?></title>
		<?php $this->head() ?>
	</head>
	<body>
	<?php $this->beginBody() ?>

	<header></header>

	<main>
		<?= $content ?>
	</main>

	<footer></footer>

	<?php $this->endBody() ?>
	</body>
</html>
<?php $this->endPage() ?>

views/phones/create.php
<?php
/**
 * Форма для добавления записи в телефонный справочник
 *
 * @var app\models\PhoneForm $phoneForm
 */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>

<?php $form = ActiveForm::begin([
	'id' => 'create-form'
]) ?>
	<div class="row">
		<?= $form->field($phoneForm, 'name') ?>
	</div>
	<div class="row">
		<?= $form->field($phoneForm, 'phone') ?>
	</div>
	<div class="row">
		<?= $form->field($phoneForm, 'email') ?>
	</div>
	<div class="row">
		<?= Html::submitButton('Добавить') ?>
	</div>
<?php ActiveForm::end() ?>

views/phones/index.php
<?php
/**
 * Отображение телефонного справочника
 *
 * @var $this yii\web\View
 * @var app\models\Phones $phones       Позиции телефонного справочника
 * @var app\models\Phones $pagination   Пагинация телефонного справочника
 */

use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use yii\bootstrap\Modal;

$this->title = 'Телефонный справочник';
?>
<div class="phonebook">
	<!--<a href="#" class="create-link" data-url="--><?//= Url::to(['/phones/create']) ?><!--">Добавить</a>-->
	<?php Modal::begin([
		'id' => 'modal-create',
		'size' => 'modal-lg',
		'clientOptions' => false,
		'toggleButton' => [
			'label' => 'Добавить',
			'tag' => 'a',
			'data-target' => '#modal-create',
			'href' => Url::to(['/phones/create']),
		]
	]);
	Modal::end() ?>
	<ul>
		<?php foreach($phones as $phone): ?>
			<li>
				<div class="col-lg-4"><?= $phone->name ?></div>
				<div class="col-lg-4"><?= $phone->phone ?></div>
				<div class="col-lg-4"><?= $phone->email ?></div>
				<?php Modal::begin([
					'id' => 'modal-update-' . $phone->id,
					'size' => 'modal-lg',
					'clientOptions' => false,
					'toggleButton' => [
						'label' => 'Редактировать',
						'tag' => 'a',
						'data-target' => '#modal-update-' . $phone->id,
						'href' => Url::to(['/phones/update', 'id' => $phone->id]),
					]
				]);
				Modal::end() ?>
				<!--<a href="#" class="update-link" data-url="--><?//= Url::to(['/phones/update', 'id' => $phone->id]) ?><!--">Редактировать</a>-->
				<a href="#" class="delete-link" data-url="<?= Url::to(['/phones/delete', 'id' => $phone->id]) ?>">Удалить</a>
			</li>
		<? endforeach ?>
	</ul>
	<?= LinkPager::widget(['pagination' => $pagination, 'class' => 'pager']) ?>
</div>

views/phones/update.php
<?php
/**
 * Форма для изменения записи в телефонном справочнике
 *
 * @var app\models\PhoneForm $phoneForm
 */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>

<?php $form = ActiveForm::begin([
	'id' => 'update-form'
]) ?>
	<div class="row">
		<?= $form->field($phoneForm, 'name') ?>
	</div>
	<div class="row">
		<?= $form->field($phoneForm, 'phone') ?>
	</div>
	<div class="row">
		<?= $form->field($phoneForm, 'email') ?>
	</div>
	<div class="row">
		<?= Html::submitButton('Сохранить') ?>
	</div>
<?php ActiveForm::end() ?>